// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// delaunator_triangulate.cpp
integers delaunator_triangulate_cpp(std::vector<double> coords);
extern "C" SEXP _delaunator_delaunator_triangulate_cpp(SEXP coords) {
  BEGIN_CPP11
    return cpp11::as_sexp(delaunator_triangulate_cpp(cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(coords)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_delaunator_delaunator_triangulate_cpp", (DL_FUNC) &_delaunator_delaunator_triangulate_cpp, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_delaunator(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
